#!/bin/sh
ACT="/tmp/.nextCMD"
CMD="dmenuc.bin"
if [ "`pwd`" != "/mnt/mmc/dmenu" ]; then 
    CMD="dmenuc.bin"
fi

touch "$ACT"

if ./$CMD; then
    if [ -f "$ACT" ]; then 
        echo "executing:" >> /tmp/stdout.txt
        cat $ACT  >> /tmp/stdout.txt
        if  ! sh $ACT >> /tmp/stdout.txt 2>> /tmp/stderr.txt; then
#           sleep 5
            echo
        fi
        rm -f "$ACT"
    fi
else
    sleep 30
fi
